# SPDX-FileCopyrightText: The Open Annihilation Authors; see COPYRIGHT
# SPDX-License-Identifier: GPL-3.0-only

cmake_minimum_required(VERSION 3.24)
project(oa_sim_unit_movement LANGUAGES CXX)
include(CTest)
add_library(oa-sim-unit-movement src/movement.cpp src/terrain.cpp)
add_library(oa::sim::unit_movement ALIAS oa-sim-unit-movement)
target_include_directories(oa-sim-unit-movement PUBLIC include)
target_link_libraries(oa-sim-unit-movement PUBLIC oa-formats-tnt oa-formats-objects3d)
target_compile_features(oa-sim-unit-movement PUBLIC cxx_std_20)
include("${CMAKE_CURRENT_LIST_DIR}/../../../cmake/OaOptions.cmake")
target_link_libraries(oa-sim-unit-movement PUBLIC oa-base-game-math)
if(TARGET oa-options)
  target_link_libraries(oa-sim-unit-movement PUBLIC oa-options)
endif()
if(BUILD_TESTING)
  add_executable(oa-unit-movement-test tests/movement_test.cpp)
  target_link_libraries(oa-unit-movement-test PRIVATE oa-sim-unit-movement)
  add_test(NAME unit-movement COMMAND oa-unit-movement-test)
endif()
if(BUILD_TESTING)
  add_executable(oa-unit-terrain-test tests/terrain_test.cpp)
  target_link_libraries(oa-unit-terrain-test PRIVATE oa-sim-unit-movement)
  add_test(NAME unit-terrain COMMAND oa-unit-terrain-test)
endif()
