# SPDX-FileCopyrightText: The Open Annihilation Authors; see COPYRIGHT
# SPDX-License-Identifier: GPL-3.0-only

enable_language(C)
add_library(oa-core-types INTERFACE)
add_library(oa::core::types ALIAS oa-core-types)
target_include_directories(oa-core-types INTERFACE include)
target_compile_features(oa-core-types INTERFACE cxx_std_20)
if(BUILD_TESTING)
  add_executable(oa-core-types-c-test tests/core_types_test.c)
  set_target_properties(oa-core-types-c-test PROPERTIES C_STANDARD 11 C_STANDARD_REQUIRED ON C_EXTENSIONS OFF)
  target_link_libraries(oa-core-types-c-test PRIVATE oa-core-types oa-options)
  add_test(NAME core-types-c COMMAND oa-core-types-c-test)
  add_executable(oa-core-types-cpp-test tests/core_types_test.cpp)
  target_link_libraries(oa-core-types-cpp-test PRIVATE oa-core-types oa-options)
  add_test(NAME core-types-cpp COMMAND oa-core-types-cpp-test)
  add_executable(oa-core-world-c-test tests/world_test.c)
  set_target_properties(oa-core-world-c-test PROPERTIES C_STANDARD 11 C_STANDARD_REQUIRED ON C_EXTENSIONS OFF)
  target_link_libraries(oa-core-world-c-test PRIVATE oa-core-types oa-options)
  add_test(NAME core-world-c COMMAND oa-core-world-c-test)
  add_executable(oa-core-world-cpp-test tests/world_test.cpp)
  target_link_libraries(oa-core-world-cpp-test PRIVATE oa-core-types oa-options)
  add_test(NAME core-world-cpp COMMAND oa-core-world-cpp-test)
endif()
